Kitting Cell: Perception Class Reference
Perception Class Reference
#include <Perception.hpp>
Public Member Functions
Perception ()
int colorThresholder (std::string)
void ReadImg (const sensor_msgs::ImageConstPtr &)
Private Attributes
ros::NodeHandle n_
ROS node handle.
image_transport::ImageTransport imgT_
sensor_imgs data to readable openCV data
image_transport::Subscriber imageSubscriber_
subscriber
cv_bridge::CvImagePtr cv_ptr_
The variable to read image data.
std::vector< int > cylinder1_ {117, 148}
image coordinates of cylinder2
std::vector< int > cylinder2_ {149, 145}
image coordinates of cylinder1
std::vector< int > cylinder3_ {146, 111}
image coordinates of cylinder0
Detailed Description
Definition at line 187 of file Perception.hpp.
Constructor & Destructor Documentation
Perception::Perception ()
Definition at line 186 of file Perception.cpp.
References imageSubscriber_, imgT_, and ReadImg().
                        : imgT_(n_) {
   // Subscribe to input video feed
   imageSubscriber_ = imgT_.subscribe("/camera/image_raw", 1,
   &Perception::ReadImg, this);
 }
Member Function Documentation
int Perception::colorThresholder (std::string color)
Definition at line 208 of file Perception.cpp.
References cv_ptr_, cylinder1_, cylinder2_, and cylinder3_.
Referenced by TEST().
{
   std::vector<int> order;
   cv::Vec3b cylinder1Color;
   cv::Vec3b cylinder2Color;
   cv::Vec3b cylinder3Color;
   std::vector<cv::Vec3b> colorVec;
   // 3D color vector of center of each cylinder
   cylinder1Color = Perception::cv_ptr_->image.at<cv::Vec3b>(
                           Perception::cylinder1_[0], Perception::cylinder1_[1]);
   cylinder2Color = Perception::cv_ptr_->image.at<cv::Vec3b>(
                           Perception::cylinder2_[0], Perception::cylinder2_[1]);
   cylinder3Color = Perception::cv_ptr_->image.at<cv::Vec3b>(
                           Perception::cylinder3_[0], Perception::cylinder3_[1]);
 // Make vector of color vectors
   colorVec.push_back(cylinder1Color);
   colorVec.push_back(cylinder2Color);
   colorVec.push_back(cylinder3Color);
 // Inialize flag. This stores the ID of the ylinder of the color being searched
 // for
   int pixIndex = 5;
   if (color =="red") {
     pixIndex = 2;
     ROS_INFO_STREAM("looking for red");
   } else if (color =="green") {
     pixIndex = 1;
     ROS_INFO_STREAM("looking for green");
   } else if (color =="blue") {
     pixIndex = 0;
     ROS_INFO_STREAM("looking for blue");
   } else {
     ROS_ERROR("INVALID COLOR INPUT!!! red, green or blue VALUES only");
     return 6;
     ros::shutdown();
   }
   if ((pixIndex == 0) || (pixIndex == 1) || (pixIndex == 2)) {
     for (int i = 0; i < 3; i++) {
       cv::Vec3b vec = colorVec[i];
       if (static_cast<int>(vec.val[pixIndex]) > 200) {
         ROS_INFO_STREAM(i);
         return pixIndex;  //  returns 0,1,2 in BGR format
       }
     }
   }
 }
void Perception::ReadImg (const sensor_msgs::ImageConstPtr & msg)
Definition at line 195 of file Perception.cpp.
References cv_ptr_.
Referenced by Perception(), and TEST().
{
   // Read the image
   try {
     cv_ptr_ = cv_bridge::toCvCopy(msg, sensor_msgs::image_encodings::BGR8);
   } catch (cv_bridge::Exception& e) {
     ROS_ERROR("cv_bridge exception: %s", e.what());
     return;
   }
 }
Member Data Documentation
ros::NodeHandle Perception::n_ private
ROS node handle.
Definition at line 190 of file Perception.hpp.
image_transport::ImageTransport Perception::imgT_ private
sensor_imgs data to readable openCV data
cv_bridge variable to convert
Definition at line 191 of file Perception.hpp.
Referenced by Perception().
image_transport::Subscriber Perception::imageSubscriber_ private
subscriber
Image Transport data
Definition at line 193 of file Perception.hpp.
Referenced by Perception().
cv_bridge::CvImagePtr Perception::cv_ptr_ private
The variable to read image data.
Definition at line 195 of file Perception.hpp.
Referenced by colorThresholder(), and ReadImg().
std::vector<int> Perception::cylinder1_ {117, 148} private
image coordinates of cylinder2
Definition at line 197 of file Perception.hpp.
Referenced by colorThresholder().
std::vector<int> Perception::cylinder2_ {149, 145} private
image coordinates of cylinder1
Definition at line 198 of file Perception.hpp.
Referenced by colorThresholder().
std::vector<int> Perception::cylinder3_ {146, 111} private
image coordinates of cylinder0
Definition at line 199 of file Perception.hpp.
Referenced by colorThresholder().
The documentation for this class was generated from the following files:
include/kitting_cell/Perception.hpp
src/Perception.cpp