Kitting Cell: kuka Class Reference
kuka Class Reference
Class to calculate forward and inverse kinematics for KUKA IIWA.
#include <kuka.hpp>
Public Member Functions
kuka ()
This is the constructor for the class.
trajectory_msgs::JointTrajectory initializeTrajectoryPoint ()
This initializes kuka::jointCommands_ to 0.0.
trajectory_msgs::JointTrajectoryPoint initializeHomePos ()
This initializes the home position for the robot.
sensor_msgs::JointState initializeJointsSub ()
This initializes the variable that takes in the joint values from the subscriber.
KDL::JntArray initializeJointsKDL ()
This initializes the joint arrays that are fed to the kinematic solvers.
KDL::Chain makeChain ()
This defines the kinematic chain for KDL.
trajectory_msgs::JointTrajectoryPoint normalizePoints (KDL::JntArray)
This normalizes the joint angles after Inverse Kinematics.
void getJoints (const sensor_msgs::JointState::ConstPtr &jointsState_)
This is the subscriber to read joint values for the robot.
KDL::JntArray evalKinematicsIK (KDL::Frame)
This performs the inverse kinematics to get joint angles from cartesian pose.
KDL::Frame evalKinematicsFK ()
This performs the forward kinematics to get cartesian pose from joint angles.
unsigned int getJointNums ()
This calculates the number of joints in the chain and also preallocates jointPosKdl_ and newJointPosKdl_ data members.
trajectory_msgs::JointTrajectory driveRobot (trajectory_msgs::JointTrajectoryPoint)
This forms the JointTrajectory message to whoch the robot is supposed to move.
KDL::JntArray returnCurrJoints ()
This returns the current joint of the robot.
Private Attributes
int id
sensor_msgs::JointState jointsState_
variable to read current joint states
KDL::Chain kinematicChain_
KDL::Chain type vaiable for robot chain.
unsigned int numJoints_
KDL::JntArray jointPosKdl_
KDL joint array current for FK.
KDL::JntArray newJointPosKdl_
KDL joint array new from IK.
KDL::Frame currCartpos_
KDL::Frame variable for current cartesianpose.
trajectory_msgs::JointTrajectory jointCommands_
trajectory_msgs::JointTrajectory variable for final jointCommands
trajectory_msgs::JointTrajectoryPoint homePos_
Detailed Description
Class to calculate forward and inverse kinematics for KUKA IIWA.
Definition at line 200 of file kuka.hpp.
Constructor & Destructor Documentation
kuka::kuka ()
This is the constructor for the class.
Definition at line 385 of file kuka.cpp.
References getJointNums(), initializeHomePos(), initializeJointsKDL(), initializeJointsSub(), initializeTrajectoryPoint(), jointPosKdl_, makeChain(), newJointPosKdl_, and numJoints_.
            {
   kuka::makeChain();
   kuka::getJointNums();
   kuka::initializeTrajectoryPoint();
   kuka::initializeHomePos();
   kuka::jointPosKdl_ = KDL::JntArray(kuka::numJoints_);
   kuka::newJointPosKdl_ = KDL::JntArray(kuka::numJoints_);
   kuka::initializeJointsKDL();
   kuka::initializeJointsSub();
 }
Member Function Documentation
trajectory_msgs::JointTrajectory kuka::initializeTrajectoryPoint ()
This initializes kuka::jointCommands_ to 0.0.
Parameters
none
Returns
trajectory_msgs::JointTrajectory type variable initialized to robot joint names, header, and time stamp
Definition at line 247 of file kuka.cpp.
References jointCommands_.
Referenced by kuka(), and TEST().
{
   //initialize names
   kuka::jointCommands_.joint_names.push_back("iiwa_joint_1");
   kuka::jointCommands_.joint_names.push_back("iiwa_joint_2");
   kuka::jointCommands_.joint_names.push_back("iiwa_joint_3");
   kuka::jointCommands_.joint_names.push_back("iiwa_joint_4");
   kuka::jointCommands_.joint_names.push_back("iiwa_joint_5");
   kuka::jointCommands_.joint_names.push_back("iiwa_joint_6");
   kuka::jointCommands_.joint_names.push_back("iiwa_joint_7");
   //initialize message header
   kuka::jointCommands_.header.seq = 0;
   //initialize message stamo
   kuka::jointCommands_.header.stamp = ros::Time::now();
   //initialize message frame id
   kuka::jointCommands_.header.frame_id = "";
   return kuka::jointCommands_;
 }
trajectory_msgs::JointTrajectoryPoint kuka::initializeHomePos ()
This initializes the home position for the robot.
Parameters
none
Returns
trajectory_msgs::JointTrajectoryPoint type variable to define robot's destination
Definition at line 265 of file kuka.cpp.
References homePos_, and numJoints_.
Referenced by kuka(), main(), and TEST().
{
   for (int i = 0; i < kuka::numJoints_; ++i) {
     if (i == 0)
     kuka::homePos_.positions.push_back(0);
     if (i == 1)
     kuka::homePos_.positions.push_back(0);
     if (i == 2)
     kuka::homePos_.positions.push_back(0);
     if (i == 3)
     kuka::homePos_.positions.push_back(-1.57);
     if (i == 4)
     kuka::homePos_.positions.push_back(0.0);
     if (i == 5)
     kuka::homePos_.positions.push_back(1.57);
     if (i == 6)
     kuka::homePos_.positions.push_back(0);
   }
   kuka::homePos_.time_from_start = ros::Duration(1.0);
   return kuka::homePos_;
 }
sensor_msgs::JointState kuka::initializeJointsSub ()
This initializes the variable that takes in the joint values from the subscriber.
Parameters
none
Returns
sensor_msgs::JointState variable to hold joint values
Definition at line 294 of file kuka.cpp.
References jointsState_, and numJoints_.
Referenced by kuka(), and TEST().
{
   for (int i = 0; i < kuka::numJoints_; ++i) {
     kuka::jointsState_.position.push_back(0.2);
   }
   return kuka::jointsState_;
 }
KDL::JntArray kuka::initializeJointsKDL ()
This initializes the joint arrays that are fed to the kinematic solvers.
Parameters
none
Returns
initialized joint arrays for KDL solvers
Definition at line 286 of file kuka.cpp.
References jointPosKdl_, newJointPosKdl_, and numJoints_.
Referenced by kuka(), and TEST().
{
   for (int i = 0; i < kuka::numJoints_; ++i) {
     kuka::jointPosKdl_(i) = 0.2;
     kuka::newJointPosKdl_(i) = 0.2;
   }
   return kuka::jointPosKdl_;
 }
KDL::Chain kuka::makeChain ()
This defines the kinematic chain for KDL.
Parameters
none
Returns
KDL::Chain variable that holds the kinematic chain
Definition at line 200 of file kuka.cpp.
References kinematicChain_.
Referenced by evalKinematicsFK(), evalKinematicsIK(), kuka(), and TEST().
{
   // Define LWR chain_
   KDL::Chain chain_;
   // base
   chain_.addSegment(KDL::Segment(KDL::Joint(KDL::Joint::None),
                                    KDL::Frame::DH_Craig1989(0, 0, 0.33989, 0)));
   // joint 1
   chain_.addSegment(KDL::Segment(KDL::Joint(KDL::Joint::RotZ),
                                    KDL::Frame::DH_Craig1989(0, -M_PI_2, 0, 0)));
   // joint 2
   chain_.addSegment(KDL::Segment(KDL::Joint(KDL::Joint::RotZ),
                               KDL::Frame::DH_Craig1989(0, M_PI_2, 0.40011, 0)));
   // joint 3
   chain_.addSegment(KDL::Segment(KDL::Joint(KDL::Joint::RotZ),
                                     KDL::Frame::DH_Craig1989(0, M_PI_2, 0, 0)));
   // joint 4
   chain_.addSegment(KDL::Segment(KDL::Joint(KDL::Joint::RotZ),
                              KDL::Frame::DH_Craig1989(0, -M_PI_2, 0.40003, 0)));
   // joint 5
   chain_.addSegment(KDL::Segment(KDL::Joint(KDL::Joint::RotZ),
                                    KDL::Frame::DH_Craig1989(0, -M_PI_2, 0, 0)));
   // joint 6
   chain_.addSegment(KDL::Segment(KDL::Joint(KDL::Joint::RotZ),
                                     KDL::Frame::DH_Craig1989(0, M_PI_2, 0, 0)));
   // joint 7 (with flange adapter)
   chain_.addSegment(KDL::Segment(KDL::Joint(KDL::Joint::RotZ),
                                    KDL::Frame::DH_Craig1989(0, 0, 0.12597, 0)));
   kuka::kinematicChain_ = chain_;
   return chain_;
 }
trajectory_msgs::JointTrajectoryPoint kuka::normalizePoints (KDL::JntArray joints)
This normalizes the joint angles after Inverse Kinematics.
Parameters
the joint array calculated frm inverse kinematics
Returns
trajectory_msgs::JointTrajectoryPoint variable tha holds joint trajectory point to move the robot to
Definition at line 362 of file kuka.cpp.
References numJoints_.
Referenced by main(), and TEST().
{
   trajectory_msgs::JointTrajectoryPoint point;
   // joints can move between -+: 172,120,172,120,172,120,170
   // double joint_bounds[] = {3.002, 2.0944,3.002, 2.0944,3.002, 2.0944, 3.002};
   for (int i = 0; i < kuka::numJoints_; ++i) {
     while (joints(i) > M_PI) {
       joints(i) -= 2*M_PI;
     }
     while (joints(i) < -M_PI) {
       joints(i) += 2*M_PI;
     }
     point.positions.push_back(joints(i));
   }
   return point;
 }
void kuka::getJoints (const sensor_msgs::JointState::ConstPtr & jointsState_)
This is the subscriber to read joint values for the robot.
Parameters
jointsState_ is the variable that holds the current joint values
Returns
void
Definition at line 231 of file kuka.cpp.
References jointsState_.
Referenced by main().
{
   for (int i = 0; i < msg->position.size(); ++i) {
     kuka::jointsState_.position[i] = msg->position[i];
   }
 }
KDL::JntArray kuka::evalKinematicsIK (KDL::Frame cartpos)
This performs the inverse kinematics to get joint angles from cartesian pose.
Parameters
the cartesian pose
Returns
KDL::JntArray type joint array calculated from IK
Definition at line 344 of file kuka.cpp.
References evalKinematicsFK(), jointPosKdl_, makeChain(), and newJointPosKdl_.
Referenced by main(), and TEST().
{
   // read subscriber
   ros::spinOnce();
   // perform forward kinematics
   kuka::evalKinematicsFK();
   // make chain
   KDL::Chain chain = kuka::makeChain();
   // initiate solvers
   KDL::ChainFkSolverPos_recursive fksolver =
                                          KDL::ChainFkSolverPos_recursive(chain);
   KDL::ChainIkSolverVel_pinv iksolverv = KDL::ChainIkSolverVel_pinv(chain);
   KDL::ChainIkSolverPos_NR iksolver(chain, fksolver, iksolverv, 100, 1e-4);
   // perform IK
   int ret = iksolver.CartToJnt(kuka::jointPosKdl_, cartpos,
                                                          kuka::newJointPosKdl_);
   return kuka::newJointPosKdl_;
 }
KDL::Frame kuka::evalKinematicsFK ()
This performs the forward kinematics to get cartesian pose from joint angles.
Parameters
none
Returns
KDL::Frame type cartesian pose from FK
Definition at line 326 of file kuka.cpp.
References currCartpos_, jointPosKdl_, jointsState_, makeChain(), and numJoints_.
Referenced by evalKinematicsIK(), and TEST().
{
   ros::spinOnce();
   // reinitialize chain.
   KDL::Chain chain = kuka::makeChain();
   // initialize solvers
   KDL::ChainFkSolverPos_recursive fksolver =
                                          KDL::ChainFkSolverPos_recursive(chain);
   KDL::Frame cartPos;
   // put joint angles in KDL format
   for (int k = 0; k < numJoints_; ++k) {
     kuka::jointPosKdl_(k) = kuka::jointsState_.position[k];
   }
   // perform FK
   bool status = fksolver.JntToCart(kuka::jointPosKdl_, cartPos);
   kuka::currCartpos_ = cartPos;
   return cartPos;
 }
unsigned int kuka::getJointNums ()
This calculates the number of joints in the chain and also preallocates jointPosKdl_ and newJointPosKdl_ data members.
Parameters
none
Returns
number of joints as unsigned int variable
Definition at line 238 of file kuka.cpp.
References jointPosKdl_, kinematicChain_, newJointPosKdl_, and numJoints_.
Referenced by kuka(), and TEST().
{
   kuka::numJoints_ = kuka::kinematicChain_.getNrOfJoints();
   //initialize joint array
   kuka::jointPosKdl_ = KDL::JntArray(numJoints_);
   //initialize joint array
   kuka::newJointPosKdl_ = KDL::JntArray(numJoints_);
   return kuka::numJoints_;
 }
trajectory_msgs::JointTrajectory kuka::driveRobot (trajectory_msgs::JointTrajectoryPoint point)
This forms the JointTrajectory message to whoch the robot is supposed to move.
Parameters
JointTrajectoryPoint containing joint angles
Returns
JointTrajectory to drive the robot
Definition at line 301 of file kuka.cpp.
References id.
Referenced by main(), and TEST().
{
   trajectory_msgs::JointTrajectory jointCmd;
   // read subscriber
   ros::spinOnce();
   // give warning (for physical robots)
   ROS_INFO_STREAM("driving");
   // point parameters
   point.time_from_start = ros::Duration(1.0);
   jointCmd.joint_names.push_back("iiwa_joint_1");
   jointCmd.joint_names.push_back("iiwa_joint_2");
   jointCmd.joint_names.push_back("iiwa_joint_3");
   jointCmd.joint_names.push_back("iiwa_joint_4");
   jointCmd.joint_names.push_back("iiwa_joint_5");
   jointCmd.joint_names.push_back("iiwa_joint_6");
   jointCmd.joint_names.push_back("iiwa_joint_7");
   jointCmd.header.seq = 0;
   jointCmd.header.stamp.sec = 0;
   jointCmd.header.stamp = ros::Time::now();
   jointCmd.header.frame_id = kuka::id++;
   // input joint coordinates
   jointCmd.points.push_back(point);
   return jointCmd;
 }
KDL::JntArray kuka::returnCurrJoints ()
This returns the current joint of the robot.
Parameters
none
Returns
KDL::JntArray type variable of joint angles
Definition at line 379 of file kuka.cpp.
References jointPosKdl_.
Referenced by TEST().
{
   KDL::JntArray joints;
   joints = kuka::jointPosKdl_;
   return kuka::jointPosKdl_;
 }
Member Data Documentation
int kuka::id private
Definition at line 202 of file kuka.hpp.
Referenced by driveRobot().
sensor_msgs::JointState kuka::jointsState_ private
variable to read current joint states
sensor_msgs::JointState tye
Definition at line 203 of file kuka.hpp.
Referenced by evalKinematicsFK(), getJoints(), and initializeJointsSub().
KDL::Chain kuka::kinematicChain_ private
KDL::Chain type vaiable for robot chain.
Definition at line 205 of file kuka.hpp.
Referenced by getJointNums(), and makeChain().
unsigned int kuka::numJoints_ private
unsigned int variable to hold number of kinematic joints
Definition at line 206 of file kuka.hpp.
Referenced by evalKinematicsFK(), getJointNums(), initializeHomePos(), initializeJointsKDL(), initializeJointsSub(), kuka(), and normalizePoints().
KDL::JntArray kuka::jointPosKdl_ private
KDL joint array current for FK.
Definition at line 208 of file kuka.hpp.
Referenced by evalKinematicsFK(), evalKinematicsIK(), getJointNums(), initializeJointsKDL(), kuka(), and returnCurrJoints().
KDL::JntArray kuka::newJointPosKdl_ private
KDL joint array new from IK.
Definition at line 209 of file kuka.hpp.
Referenced by evalKinematicsIK(), getJointNums(), initializeJointsKDL(), and kuka().
KDL::Frame kuka::currCartpos_ private
KDL::Frame variable for current cartesianpose.
Definition at line 210 of file kuka.hpp.
Referenced by evalKinematicsFK().
trajectory_msgs::JointTrajectory kuka::jointCommands_ private
trajectory_msgs::JointTrajectory variable for final jointCommands
Definition at line 211 of file kuka.hpp.
Referenced by initializeTrajectoryPoint().
trajectory_msgs::JointTrajectoryPoint kuka::homePos_ private
Definition at line 213 of file kuka.hpp.
Referenced by initializeHomePos().
The documentation for this class was generated from the following files:
include/kitting_cell/kuka.hpp
src/kuka.cpp