Kitting Cell: test/kukaTests.cpp File Reference
kukaTests.cpp File Reference
This is the file for testing the methods of the kuka class.
#include <gtest/gtest.h>
#include <std_msgs/UInt8.h>
#include <std_msgs/Bool.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Int16.h>
#include <ros/ros.h>
#include <sensor_msgs/JointState.h>
#include <trajectory_msgs/JointTrajectory.h>
#include <trajectory_msgs/JointTrajectoryPoint.h>
#include <kdl/chain.hpp>
#include <kdl/chainfksolver.hpp>
#include <kdl/chainiksolver.hpp>
#include <kdl/chainfksolverpos_recursive.hpp>
#include <kdl/chainiksolvervel_pinv.hpp>
#include <kdl/chainiksolverpos_nr.hpp>
#include <kdl/chainjnttojacsolver.hpp>
#include "kuka.hpp"
Functions
TEST (initializeTrajectoryPointTest, CheckJointNames)
TEST (initializeTrajectoryPointTest, CheckTrajectoryheader)
TEST (initializeHomePosTest, CheckHomePos)
TEST (initializeJointsSubTest, CheckJointSub)
TEST (initializeJointsKDLTest, CheckJointsKDL)
TEST (makeChainTest, CheckChain)
TEST (EvaluateKinematics, CheckFK)
TEST (GetJointNumbersTest, CheckgetJointNums)
TEST (normalizePointsTest, ChecknormalizedPoints)
TEST (EvaluateKinematicsTest, CheckIK)
TEST (driveRobotTest, names)
TEST (driveRobotTest, properties)
TEST (returnCurrJointsTest, joints)
Detailed Description
This is the file for testing the methods of the kuka class.
Author
Royneal Rayess [royneal] - driver
Bharat Mathur [bharatm11] - navigator
Date
13 Dec 2018
Copyright
2018 Royneal Rayess, Bharat Mathur
Definition in file kukaTests.cpp.
Function Documentation
TEST (initializeTrajectoryPointTest , CheckJointNames)
Definition at line 195 of file kukaTests.cpp.
References kuka::initializeTrajectoryPoint().
{
   ros::Time::init();
   trajectory_msgs::JointTrajectory obj;  // initialize to joint names
   kuka robot;
   obj = robot.initializeTrajectoryPoint();
   EXPECT_STREQ("iiwa_joint_1", obj.joint_names[0].c_str());
   EXPECT_STREQ("iiwa_joint_2", obj.joint_names[1].c_str());
   EXPECT_STREQ("iiwa_joint_3", obj.joint_names[2].c_str());
   EXPECT_STREQ("iiwa_joint_4", obj.joint_names[3].c_str());
   EXPECT_STREQ("iiwa_joint_5", obj.joint_names[4].c_str());
   EXPECT_STREQ("iiwa_joint_6", obj.joint_names[5].c_str());
   EXPECT_STREQ("iiwa_joint_7", obj.joint_names[6].c_str());
   EXPECT_EQ(0, obj.header.seq);
 }
TEST (initializeTrajectoryPointTest , CheckTrajectoryheader)
Definition at line 211 of file kukaTests.cpp.
References kuka::initializeTrajectoryPoint().
{
   ros::Time::init();
   trajectory_msgs::JointTrajectory obj;  // initialize to joint names
   kuka robot;
   obj = robot.initializeTrajectoryPoint();
   EXPECT_EQ(0, obj.header.seq);
 }
TEST (initializeHomePosTest , CheckHomePos)
Definition at line 219 of file kukaTests.cpp.
References kuka::initializeHomePos().
{
   ros::Time::init();
   trajectory_msgs::JointTrajectoryPoint joint;
   kuka robot;
   joint = robot.initializeHomePos();
   EXPECT_EQ(0, joint.positions[0]);
   EXPECT_EQ(0, joint.positions[1]);
   EXPECT_EQ(0, joint.positions[2]);
   EXPECT_EQ(-1.57, joint.positions[3]);
   EXPECT_EQ(0, joint.positions[4]);
   EXPECT_EQ(1.57, joint.positions[5]);
   EXPECT_EQ(0, joint.positions[6]);
 }
TEST (initializeJointsSubTest , CheckJointSub)
Definition at line 233 of file kukaTests.cpp.
References kuka::initializeJointsSub().
{
   ros::Time::init();
   sensor_msgs::JointState obj;  // initialize to joint names
   kuka robot; ros::NodeHandle nh_;
   obj = robot.initializeJointsSub();
   EXPECT_EQ(0.2, obj.position[0]);
 }
TEST (initializeJointsKDLTest , CheckJointsKDL)
Definition at line 241 of file kukaTests.cpp.
References kuka::initializeJointsKDL().
{
   ros::Time::init();
   KDL::JntArray obj;  // initialize to joint names
   kuka robot;
   obj = robot.initializeJointsKDL();
   EXPECT_EQ(0.2, obj(0));
 }
TEST (makeChainTest , CheckChain)
Definition at line 249 of file kukaTests.cpp.
References kuka::makeChain().
{
   ros::Time::init();
   KDL::Chain obj;  // initialize to joint names
   kuka robot;
   obj = robot.makeChain();
   int segmnt = obj.getNrOfSegments();
   EXPECT_EQ(8, segmnt);
 }
TEST (EvaluateKinematics , CheckFK)
Definition at line 258 of file kukaTests.cpp.
References kuka::evalKinematicsFK().
{
   ros::Time::init();
   kuka ku;
   KDL::Frame obj = ku.evalKinematicsFK();
   std::cout << obj.p[0];
   EXPECT_NEAR(0.104714, obj.p[0], 0.1);
 }
TEST (GetJointNumbersTest , CheckgetJointNums)
Definition at line 266 of file kukaTests.cpp.
References kuka::getJointNums().
{
   ros::Time::init();
   kuka robot;
   unsigned int obj = robot.getJointNums();
   EXPECT_EQ(7, obj);
 }
TEST (normalizePointsTest , ChecknormalizedPoints)
Definition at line 273 of file kukaTests.cpp.
References kuka::initializeJointsKDL(), and kuka::normalizePoints().
{
   ros::Time::init();
   kuka ku;
   KDL::JntArray joints = ku.initializeJointsKDL();
   trajectory_msgs::JointTrajectoryPoint obj;
   obj = ku.normalizePoints(joints);
   EXPECT_NEAR(0.2, obj.positions[1], 0.0001);
 }
TEST (EvaluateKinematicsTest , CheckIK)
Definition at line 282 of file kukaTests.cpp.
References kuka::evalKinematicsFK(), and kuka::evalKinematicsIK().
{
   ros::Time::init();
   kuka ku;
   KDL::Frame cartpos = ku.evalKinematicsFK();
   KDL::JntArray jointpositions_new = ku.evalKinematicsIK(cartpos);
   EXPECT_NEAR(0.2, jointpositions_new(0), 0.001);
 }
TEST (driveRobotTest , names)
Definition at line 290 of file kukaTests.cpp.
References kuka::driveRobot(), kuka::evalKinematicsFK(), kuka::evalKinematicsIK(), and kuka::normalizePoints().
{
   ros::Time::init();
   kuka ku;
   KDL::Frame cartpos = ku.evalKinematicsFK();
   KDL::JntArray jointpositions_new = ku.evalKinematicsIK(cartpos);
   trajectory_msgs::JointTrajectoryPoint obj =
                                         ku.normalizePoints(jointpositions_new);
   trajectory_msgs::JointTrajectory obj2 = ku.driveRobot(obj);
   EXPECT_STREQ("iiwa_joint_1", obj2.joint_names[0].c_str());
   EXPECT_STREQ("iiwa_joint_2", obj2.joint_names[1].c_str());
   EXPECT_STREQ("iiwa_joint_3", obj2.joint_names[2].c_str());
   EXPECT_STREQ("iiwa_joint_4", obj2.joint_names[3].c_str());
   EXPECT_STREQ("iiwa_joint_5", obj2.joint_names[4].c_str());
   EXPECT_STREQ("iiwa_joint_6", obj2.joint_names[5].c_str());
   EXPECT_STREQ("iiwa_joint_7", obj2.joint_names[6].c_str());
 }
TEST (driveRobotTest , properties)
Definition at line 307 of file kukaTests.cpp.
References kuka::driveRobot(), kuka::evalKinematicsFK(), kuka::evalKinematicsIK(), and kuka::normalizePoints().
{
   ros::Time::init();
   kuka ku;
   KDL::Frame cartpos = ku.evalKinematicsFK();
   KDL::JntArray jointpositions_new = ku.evalKinematicsIK(cartpos);
   trajectory_msgs::JointTrajectoryPoint obj =
                                         ku.normalizePoints(jointpositions_new);
   trajectory_msgs::JointTrajectory obj2 = ku.driveRobot(obj);
   EXPECT_EQ(0, obj2.header.seq);
 }
TEST (returnCurrJointsTest , joints)
Definition at line 318 of file kukaTests.cpp.
References kuka::returnCurrJoints().
{
   ros::Time::init();
   kuka ku;
   KDL::JntArray obj =  ku.returnCurrJoints();
   EXPECT_NEAR(0.2, obj(0), 0.001);
 }